global:
  gba_included: false
  log_transform: false
  pd_only: true
  outlier_handling: none

projectids:
  "PPMI 145":
    log_transform: true

testnames:
  "C1QTNF1_6304-8_3":
    outlier_handling: std
  "GRN_4992-49_1":
    outlier_handling: std
  "ITGB2_12750-9_3":
    outlier_handling: std